In [1]:
import pandas as pd

In [2]:
ifile1 = "Resources/schools_complete.csv"
ifile2 = "Resources/students_complete.csv"

school_data = pd.read_csv(ifile1)
student_data = pd.read_csv(ifile2)

cd = pd.merge(student_data, school_data, how = 'left',on = ['school_name','school_name'])

cd.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [4]:
tsch = len(cd['school_name'].unique())
tst = cd['student_name'].count()
tb = 0

39170

In [3]:
school_group = cd.groupby('school_name')
school_group.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
2917,2917,Amy Jacobs,F,10th,Figueroa High School,85,87,1,District,2949,1884411
2918,2918,Nathan Campbell,M,12th,Figueroa High School,97,84,1,District,2949,1884411
2919,2919,Randall Stewart,M,12th,Figueroa High School,67,77,1,District,2949,1884411
2920,2920,Jennifer Brown,F,9th,Figueroa High School,97,64,1,District,2949,1884411
2921,2921,Denise Lopez,F,10th,Figueroa High School,79,64,1,District,2949,1884411
5866,5866,Jamie Montgomery,F,12th,Shelton High School,70,91,2,Charter,1761,1056600
5867,5867,Shannon Phillips,F,10th,Shelton High School,84,71,2,Charter,1761,1056600
5868,5868,Todd Barber,M,11th,Shelton High School,95,99,2,Charter,1761,1056600
5869,5869,Desiree King,F,12th,Shelton High School,76,95,2,Charter,1761,1056600
5870,5870,Melissa Roberts,F,10th,Shelton High School,71,82,2,Charter,1761,1056600
7627,7627,Russell Davis,M,10th,Hernandez High School,70,88,3,District,4635,3022020
7628,7628,Timothy Walker,M,12th,Hernandez High School,97,93,3,District,4635,3022020
7629,7629,Katie Johnston,F,12th,Hernandez High School,83,81,3,District,4635,3022020
7630,7630,Joann Oconnell,F,12th,Hernandez High School,77,91,3,District,4635,3022020
7631,7631,Sarah Alexander,F,10th,Hernandez High School,84,93,3,District,4635,3022020
12262,12262,Heather Wright,F,11th,Griffin High School,79,68,4,Charter,1468,917500
12263,12263,Elizabeth Goodwin,F,10th,Griffin High School,91,81,4,Charter,1468,917500
12264,12264,Michelle Wong,F,9th,Griffin High School,78,89,4,Charter,1468,917500
12265,12265,Scott Roth MD,M,11th,Griffin High School,91,85,4,Charter,1468,917500
12266,12266,Billy Wilson,M,12th,Griffin High School,76,83,4,Charter,1468,917500
13730,13730,Kelli Anderson,F,10th,Wilson High School,84,71,5,Charter,2283,1319574
13731,13731,Russell Ramirez,M,10th,Wilson High School,72,87,5,Charter,2283,1319574
13732,13732,Eric Butler,M,10th,Wilson High School,97,82,5,Charter,2283,1319574
13733,13733,Warren Kerr,M,11th,Wilson High School,93,68,5,Charter,2283,1319574
13734,13734,Gail Hall,F,9th,Wilson High School,79,72,5,Charter,2283,1319574
...,...,...,...,...,...,...,...,...,...,...,...
23274,23274,Alec Davis,M,9th,Pena High School,91,75,9,Charter,962,585858
23275,23275,Michael Meyer,M,10th,Pena High School,94,76,9,Charter,962,585858
23276,23276,Donald Gutierrez,M,11th,Pena High School,98,91,9,Charter,962,585858
23277,23277,Travis Chavez,M,11th,Pena High School,78,71,9,Charter,962,585858
23278,23278,Sheena Ball,F,12th,Pena High School,87,92,9,Charter,962,585858
24236,24236,Aaron Johnson,M,10th,Wright High School,89,72,10,Charter,1800,1049400
24237,24237,Kimberly Hamilton,F,10th,Wright High School,84,93,10,Charter,1800,1049400
24238,24238,Ashley Johns,F,10th,Wright High School,88,88,10,Charter,1800,1049400
24239,24239,Stephanie Donovan,F,10th,Wright High School,75,84,10,Charter,1800,1049400
24240,24240,Cynthia Guzman,F,11th,Wright High School,93,82,10,Charter,1800,1049400
26036,26036,Sherry Jenkins,F,11th,Rodriguez High School,74,81,11,District,3999,2547363
26037,26037,Kimberly Calderon,F,10th,Rodriguez High School,80,86,11,District,3999,2547363
26038,26038,William Brady,M,11th,Rodriguez High School,97,62,11,District,3999,2547363
26039,26039,Jacob Padilla,M,11th,Rodriguez High School,79,73,11,District,3999,2547363
26040,26040,Paula Maldonado,F,10th,Rodriguez High School,96,92,11,District,3999,2547363
30035,30035,Lisa Casey,F,12th,Johnson High School,87,87,12,District,4761,3094650
30036,30036,Jessica Lopez,F,9th,Johnson High School,98,62,12,District,4761,3094650
30037,30037,Anna Wilkins,F,11th,Johnson High School,89,77,12,District,4761,3094650
30038,30038,Andrew Smith,M,9th,Johnson High School,66,85,12,District,4761,3094650
30039,30039,Robert Allison,M,11th,Johnson High School,63,85,12,District,4761,3094650
34796,34796,Michael Mercado,M,9th,Ford High School,66,94,13,District,2739,1763916
34797,34797,Stephen Wolf,M,11th,Ford High School,68,63,13,District,2739,1763916
34798,34798,Bonnie Hughes,F,12th,Ford High School,73,59,13,District,2739,1763916
34799,34799,Melissa Smith,F,11th,Ford High School,88,58,13,District,2739,1763916
34800,34800,Brian Mitchell,M,10th,Ford High School,96,55,13,District,2739,1763916
37535,37535,Norma Mata,F,10th,Thomas High School,76,76,14,Charter,1635,1043130
37536,37536,Cody Miller,M,11th,Thomas High School,84,82,14,Charter,1635,1043130
37537,37537,Erik Snyder,M,9th,Thomas High School,80,90,14,Charter,1635,1043130
37538,37538,Tanya Martinez,F,9th,Thomas High School,71,69,14,Charter,1635,1043130
37539,37539,Noah Erickson,M,9th,Thomas High School,86,76,14,Charter,1635,1043130

In [5]:

school_group.agg({
    'reading_score': ['mean'],
    'math_score':['mean']
})

                      reading_score math_score
                               mean       mean
school_name
Bailey High School        81.033963  77.048432
Cabrera High School       83.975780  83.061895
Figueroa High School      81.158020  76.711767
Ford High School          80.746258  77.102592
Griffin High School       83.816757  83.351499
Hernandez High School     80.934412  77.289752
Holden High School        83.814988  83.803279
Huang High School         81.182722  76.629414
Johnson High School       80.966394  77.072464
Pena High School          84.044699  83.839917
Rodriguez High School     80.744686  76.842711
Shelton High School       83.725724  83.359455
Thomas High School        83.848930  83.418349
Wilson High School        83.989488  83.274201
Wright High School        83.955000  83.682222